---
services:

  #-------------------------------------------------------------------
  # api_server is a nginx unit server that serves as a proxy for fastapi 
  # in the same container
  api_server: 
    ports:
      - 81:80


  #-------------------------------------------------------------------
  # otel_collector is a opentelemetry collector that receives traces 
  # and metrics from api_server
  #   and sends them to:
  #     - dev: jaeger local container
  #     - prod: otlp collector in the cloud, like newrelic, datadog, etc.
  otel_collector:
    ports:
      #- 1888:1888 # pprof extension
      #- 8888:8888 # Prometheus metrics exposed by the collector
      #- 8889:8889 # Prometheus exporter metrics
      #- 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      #- 55679:55679 # zpages extension
 

  #-------------------------------------------------------------------
  # jaeger is a jaeger all-in-one container that receives traces 
  # from otel_collector and serves as a UI for viewing traces
  #  it is only used in dev environment
  jaeger:
    ports:
      - 16686:16686
      #- 4317:4317
      #- 4318:4318
