---
name: super_linter

on:
  release:
    types: [released]
  pull_request:
    branches: [master, main]

  workflow_dispatch:
      
# set the run-name 
run-name: ${{ github.ref_name }} -> super_linter (
  ${{ github.run_attempt }}
  )

permissions: {}

jobs:
  super_linter:

    name: super_linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:

      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Check execution environment
        id: check_env
        run: |
          if [ "$ACT" = "true" ]; then
            echo "is_act=true" >> $GITHUB_OUTPUT
          else
            echo "is_act=false" >> $GITHUB_OUTPUT
          fi
            

      - name: Super-Linter on ACT
        if: steps.check_env.outputs.is_act == 'true'
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          RUN_LOCAL: true


      - name: Super-Linter on other environments (like github)
        if: steps.check_env.outputs.is_act == 'false'
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  